#!/usr/bin/env bash
# Script transfers a file from a client to a server
if [ "$4" == "" ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit
fi
path="$1"
ip="$2"
user="$3"
pass="$4"
scp -i "$pass" "$path" "$user@$ip":~
