#!/usr/bin/env bash
# Script installs ngingx, and creates temp html index file
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html/
echo "Holberton School says hello" | sudo tee index.html
service nginx start
