#!/usr/bin/env bash
# Script configures ubuntu server
apt-get -y update
apt-get install nginx
ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html/
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
service nginx start
sed '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
service nginx restart
