#!/usr/bin/env bash
# Script configures ubuntu server load-balancer
apt-get -y update && apt-get -y install haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
echo -ne "backend web-backend\n\tbalance roundrobin\n\tserver 653-web-01 35.196.108.226:80 check\n\tserver 653-web-02 34.74.255.195:80 check\n\nfrontend front\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend" | sudo tee -a /etc/haproxy/haproxy.cfg
service haproxy start
