#!/usr/bin/env bash
# script manages another process
if [ $# -ne 1 ]; then
    echo "Usage: manage_my_process {start|stop|restart}"
    exit 1
fi
if [ "$1" = "start" ]; then
    echo "manage_my_process started"
    ./manage_my_process &
    sudo bash -c 'echo "$$" > /var/run/my_process.pid'
elif [ "$1" = "stop" ]; then
    echo "manage_my_process stopped"
    sudo rm /var/run/my_process.pid
    pkill -f "./manage_my_process"
elif [ "$1" = "restart" ]; then
    pkill -f "./manage_my_process"
    sudo rm /var/run/my_process.pid
    ./manage_my_process &
    sudo bash -c 'echo "$$" > /var/run/my_process.pid'
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
    exit 1
fi
