#!/usr/bin/env bash
# script configures an ubuntu server with certain requirements
cp /etc/hosts ~/hosts.new
sed -i "/127.0.0.1/ s/.*/127.0.0.2 localhost/g" ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
