#!/usr/bin/env bash
# Script fixes container so that nginx is running as the nginx user
chown nginx:nginx /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
