#!/usr/bin/env bash
# Script fixes container so that nginx is running as the nginx user
pkill apache2
chown -R nginx:nginx /etc/nginx
chmod 777 /etc/nginx/nginx.conf
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
